# Generated by Django 4.0.1 on 2022-03-06 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='tittle',
            new_name='email',
        ),
        migrations.RemoveField(
            model_name='product',
            name='hunter',
        ),
        migrations.RemoveField(
            model_name='product',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.RemoveField(
            model_name='product',
            name='votes_total',
        ),
    ]
