# Generated by Django 4.0.1 on 2022-03-09 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DoctorProffesion', models.CharField(max_length=255)),
                ('Location', models.CharField(max_length=200)),
                ('Sex', models.CharField(max_length=200)),
                ('Meeting_type', models.TextField(verbose_name=100)),
            ],
        ),
    ]
